### ISSUE TITLE
gitbook/compass does not point to the correct docs

### ISSUE THREAD

**Issue by mabdh** [odpf/compass#118]
**Describe the bug**
[odpf.gitbook.io/compass/](https://odpf.gitbook.io/compass/) not showing the correct compass docs but redirect request to https://odpf.gitbook.io/raccoon/compass instead.

**To Reproduce**
1. Go to [compass](https://github.com/odpf/compass)
2. Click on gitbook link below About section

**Expected behavior**
The link https://odpf.gitbook.io/compass/ should show the correct gitbook compass docs

**Screenshots**

**Additional context**
Need @ravisuhag help to check this 🙏🏼

**Comment by ravisuhag** [comment]
This is fixed now.

**Comment by mabdh** [comment]
> This is fixed now.

thanks @ravisuhag 🙏🏼
