### ISSUE TITLE
CLI Support for Compass Users

### ISSUE THREAD

**Issue by GrayFlash** [odpf/compass#123]
**Is your feature request related to a problem? Please describe.**
It will be a better user experience if we can add more support for CLI commands for tasks with the compass.

**Describe the solution you'd like**
A set of commands that help user make API requests from CLI itself.
For example:
```
compass assets list/create/post/delete --parameters
compass discussions list/create/post/delete --parameters
```

**Comment by GrayFlash** [comment]
To cover up the API paths the following commands are recommended:

- compass assets list --params  (api path:  /v1beta1/assets )
- compass assets post  -patch (optional flag) --body body
- compass assets view/get --id <id> --stargazers (optional flags)
- compass assets view/get versions --id <id> (optional flags) --version <version>
- compass assets delete --id <id>
- compass discussion list (Q: should we use this command with an optional param <id> or flag --id to get Discussion for a specified ID or shall we have those with a separate get command where we specify id to get assets/discussion etc compass get Discussion/Assets/.. <id> ??? ).
- cont..
   compass discussion list (optional flags) --filters <filter_string>
- compass discussion create --body <body> (api path: /v1beta1/discussions post req).
- compass discussion comments --id <id>
- compass discussion comments --discussionID <discussionID> (optional flags) --filters <filter_string>
- compass discussion comments --discussionID <discussionID> --comment_body <comment_body> (Q: Any name suggestions for this one. This one will add a comment to the discussion. Uses same API path as the previous one so thought having --comment_body <comment_body> as an optional flag should work. But I think it is not intutive from user POV)
- compass discussion comments create/delete/view/update --discussionID <discussionID> (optional flags) --comment_id <comment_id> --comment_body <comment_body>  (Alternate for previous one as well)
- compass discussions view/get --id <id> -patch

There are more commands that will be needed, but to clear up the approach these 2 sets seems fine. 

wdyt @ravisuhag @StewartJingga @mabdh @scortier @ishanarya0 ?? feel free to add any additional suggestions.

**Comment by ravisuhag** [comment]
@GrayFlash i think we can avoid comments commands. A single discussion view command should return all comments. And we can avoid all individual comments commands.
