### ISSUE TITLE
Moving GetTypes from fetching from elasticsearch to fetching from postgres

### ISSUE THREAD

**Issue by mabdh** [odpf/compass#138]
**Is your feature request related to a problem? Please describe.**
Currently we are getting number of types from elasticsearch, but due to the changes of how we store the index (we use service as index instead of type as index), there is no simple approach to calculate/aggregate number of types of assets. Since we have a postgres as our main storage, we can leave elasticsearch purely for discovery and count the type from postgres as a source of truth.

**Describe the solution you'd like**
Fetching count of types from assets in postgres

**Comment by StewartJingga** [comment]
When fetching from postgres, we can also add feature to filter, similar with `GetAllAssets`. wdyt? @mabdh

**Comment by mabdh** [comment]
@StewartJingga yes can do that, what kind of filter do you have in mind?
