### ISSUE TITLE
feat: Asset's Status

### ISSUE THREAD

**Issue by StewartJingga** [odpf/compass#170]
**Is your feature request related to a problem? Please describe.**

There is a need in our setup that requires to store `status` of an asset.
We have a few `job` type assets and we want to update their status everytime they `start`, `finished`, `failed`, etc.

We also want to store it in historical/log manner because we want the status revision to be listed out later.
So basically an `asset` can have multiple statuses which `compass` can provide the API to store.

When `status`-es is already populated, we can then:
- show list of statuses when fetching an asset
- enrich lineage graph response to include asset status

**Describe the solution you'd like**

### 1. New status on `asset` package to represent asset's status
```
type Status struct {
	ID        string                 `json:"id"`
	AssetURN  string                 `json:"asset_urn"`
	Status    string                 `json:"status"`
	Metadata  map[string]interface{} `json:"metadata"`
	CreatedAt time.Time              `json:"created_at"`
}

type Asset struct {
        ...
	Statuses        []Status                 `json:"statuses"`
}
```

#### New endpoint to create or add a new status
`[POST] /v1beta1/asset/{urn}/status`
```
{
  "status": "COMPLETED" // can be any value
  "timestamp": "2022-09-02T07:09:24" // in utc
  "metadata": { // map to store extra information
    "foo": "bar",
    "foo_number": 8,
    "foo_bool": true
  }
}
```

### 2. Modify lineage to show asset's latest status

Current lineage API response is showing list of relations. To be able to show asset's latest status we need our lineage API to return list of assets instead.

Current response
```
{
  "data": [
    {
      "source": "my-input-1",
      "target": "my-job-1"
    },
    {
      "source": "my-job-1",
      "target": "my-output-1"
    }
  ]
}
```
New response
```
{
  "nodes": [
    {
      "urn": "my-input-1",
      "upstreams": [],
      "downstreams": [
        {"urn": "my-job-1"},
      ]
    },
    {
      "urn": "my-job-1",
      "latest_status": {
        "status": "COMPLETED",
        "created_at": "2020-12-12T19:10:10",
        "metadata": {
          "job_url": "https://myjobrun.com"
        }
      },
      "upstreams": [
        {"urn": "my-input-1"},
      ],
      "downstreams": [
        {"urn": "my-output-1"},
      ]
    },
    {
      "urn": "my-output-1",
      "upstreams": [
        {"urn": "my-job-1"},
      ],
    }
  ]
}
```

## Decisions
Going with all the approaches but renaming `Status` to `Probe` as suggested [here](https://github.com/odpf/compass/issues/170#issuecomment-1244873729).

```
type Probe struct {
	ID        string                 `json:"id"`
	AssetURN  string                 `json:"asset_urn"`
	Status    string                 `json:"status"`
	Metadata  map[string]interface{} `json:"metadata"`
	Timestamp  time.Time `json:"timestamp"`
	CreatedAt time.Time              `json:"created_at"`
}

type Asset struct {
        ...
	Probes        []Probe                 `json:"probes"`
}
```

#### New endpoint to create or add a new status
`[POST] /v1beta1/assets/{urn}/probes`
```
{
  "status": "COMPLETED" // can be any value
  "timestamp": "2022-09-02T07:09:24" // in utc
  "metadata": { // map to store extra information
    "foo": "bar",
    "foo_number": 8,
    "foo_bool": true
  }
}
```

**Comment by ravisuhag** [comment]
We can make it a bit more generic by creating `probe` as an entity instead of direct status. And `status` can go as one field on the `probe`. That will allow us to extend probes to capture more signals about the assets.

**Comment by StewartJingga** [comment]
+1

> We can make it a bit more generic by creating `probe` as an entity instead of direct status. And `status` can go as one field on the `probe`. That will allow us to extend probes to capture more signals about the assets.

+1 on renaming the main model to Probe

**Comment by sudo-suhas** [comment]
> Modify lineage to show asset's latest status

On this, I would like to propose that we return an asset status summary instead. The latest run might not always be a useful indicator as a previous failed run can get buried. The failed job could still be responsible for faulty output downstream. 

So here is what I am proposing instead - return the asset's aggregated status info along with the details of the latest run:

```json
{
  "...": "...",
  "probe_info": {
    "summary": {
      "SUCCESS": {
        "count": 8,
        "percent": 80,
        "last_instance_time": "2020-12-12T19:10:10"
      },
      "FAILED": {
        "count": 2,
        "percent": 20,
        "last_instance_time": "2020-12-11T19:10:10"
      },
      "latest_status": {
        "status": "COMPLETED",
        "created_at": "2020-12-12T19:10:10",
        "metadata": {
          "job_url": "https://myjobrun.com"
        }
      }
    }
  }
}
```

As to how we decide the recency, one way I can think of is to consider a maximum of 10 runs in the last 1 month.

**Comment by ravisuhag** [comment]
@sudo-suhas You are right that one probe might not always be useful. ButI thinks ownership to decide should lie with the source system. And they should push the status of the asset after this computation. Instead of Compass generalizing it for all systems. In this API, compass can still return the last 10 runs and UI can decide how to show it. But I think we should still rely on status itself and not aggregate the logic. WDYT?

**Comment by sudo-suhas** [comment]
> they should push the status of the asset after this computation

could you elaborate on this? since we are likely hooking into the API that would run after a single run, aggregating might not be possible.

Additionally, we are already associating a special significance to asset run/probe status hence the original proposal to include the latest status in the lineage.

> In this API, compass can still return the last 10 runs and UI can decide how to show it. But I think we should still rely on status itself and not aggregate the logic.

How about just developing a `/probe/search` API instead that supports specifying asset URNs, `newer_than` and `max_probes` as part of the filters?

**Comment by sudo-suhas** [comment]
Discussed with @ravisuhag, here are the discussion notes:
- There was some confusion regarding the suggestion in https://github.com/odpf/compass/issues/170#issuecomment-1264841390, while the approach is agreeable on a high level, we might not be able to identify the proper final structure for the `probe_info`. 
  - The `probe` model is intended to be extendable and although we only have `status` right now, we expect to add more data points.
  - Therefore, returning the summary for `status` might not be appropriate.
  - To start with, we will only return the `latest` probe but keep it extendable to introduce helpful data points for visualising live lineage. As mentioned, this data point is not the best indicator for a job's health but we will just implement as part of the first cut.
- Have concerns regarding the proposed `/probe/search` endpoint that might need to accept high number of asset URNs that can go up to 100s.

Regarding the outcome, we will be having the following response structure for lineage:

```json
{
  "nodes": [
    {
      "urn": "my-input-1",
      "upstreams": [],
      "downstreams": [
        {"urn": "my-job-1"},
      ]
    },
    {
      "urn": "my-job-1",
      "probes": {
        "latest": {
          "status": "COMPLETED",
          "created_at": "2020-12-12T19:10:10",
          "metadata": {
            "job_url": "https://myjobrun.com"
          }
        }
      },
      "upstreams": [
        {"urn": "my-input-1"},
      ],
      "downstreams": [
        {"urn": "my-output-1"},
      ]
    },
    {
      "urn": "my-output-1",
      "upstreams": [
        {"urn": "my-job-1"},
      ],
    }
  ]
}
```

We will introduce a `summary` field under `probes` in the future once we have clarity on what the summary should look like.

cc: @StewartJingga
