### ISSUE TITLE
url field is always empty even after inserting/upserting

### ISSUE THREAD

**Issue by StewartJingga** [odpf/compass#187]
**Describe the bug**
When upserting an asset via `[PUT | PATCH] /v1beta1/assets` and fetching it back via `[GET] /v1beta1/assets/{urn}`, the `url` field is always empty even when we already define it when upserting.

`[PATCH] /v1beta1/assets`
```
{
  "urn": "sample-urn",
  "url": "http://sample-url.com"
}
```
`[GET] /v1beta1/assets/sample-urn`
```
{
  "urn": "sample-urn"
}
```

**To Reproduce**
1. Upsert an asset via `[PUT | PATCH] /v1beta1/assets` with filled `url`
2. Fetch the same asset via `[GET] /v1beta1/assets/{urn}`
3. See `url` is still empty

**Expected behavior**
`url` should be returned if it has been upserted.

**Comment by sudo-suhas** [comment]
Closed via #209
