### ISSUE TITLE
fetch Asset.Data in search results

### ISSUE THREAD

**Issue by bsushmith** [odpf/compass#196]
**Is your feature request related to a problem? Please describe.**
[SearchResult](https://github.com/odpf/compass/blob/main/core/asset/discovery.go#L41-L49) does not have `Data` attribute. If we want to return and show some details from the Asset Data, that cannot be currently returned through the search results. 

**Describe the solution you'd like**
Add `Data` attribute to SearchResult so that Asset Data can be returned through the search API.

**Comment by sudo-suhas** [comment]
Can we make this opt-in? `data` can contain quite a lot of information that can significantly increase the size of the response.

**Comment by ravisuhag** [comment]
@bsushmith @sudo-suhas @StewartJingga I think we should keep search results very lean and search should only be used for full text search. Search's intention should not be to return all data. List API should take care of this.
Similar point for this.  #203  
We can close this issue for now that it is included. I will try to sum up search vs list in another issue.
