### ISSUE TITLE
ability to filter assets based on multiple nested data values in `GetAllAssets`

### ISSUE THREAD

**Issue by bsushmith** [odpf/compass#198]
**Is your feature request related to a problem? Please describe.**
In the `v1beta1/assets` [api](https://github.com/odpf/proton/blob/main/odpf/compass/v1beta1/service.proto#L261), we can filter based on [query fields](https://github.com/odpf/proton/blob/main/odpf/compass/v1beta1/service.proto#L886). Even though multiple query_fields can be supplied in the request, only one query value is taken. 

For example -
with this API - 
```text
v1beta1/assets?types=table&q_fields=data.landscape.properties.entity,data.landscape.properties.attribute&q=mkns
```
It is possible to build a filter query like this ✅  - 
```sql
WHERE type IN ('table') 
AND (data->'landscape'->'properties'->>'entity' ILIKE '%mkns%' 
OR data->'landscape'->'properties'->>'attribute' ILIKE '%mkns%')
```

But if we want to build a query like below, it is currently not possible. ❌
```sql
WHERE type IN ('table') 
AND (data->'landscape'->'properties'->>'entity'= '%abcd%' 
OR data->'landscape'->'properties'->>'entity' = '%mkns%')
```

**Describe the solution you'd like**
Make the [`Filter.Data`](https://github.com/odpf/compass/blob/main/core/asset/filter.go#L18) field type to be `map[string][]string`, and in [this](https://github.com/odpf/compass/blob/main/internal/store/postgres/asset_repository.go#L830) block, handle it accordingly.

**Describe alternatives you've considered**
One of the alternative is to let the caller of this API, call it multiple times with different filters - but that would defeat the purpose of sorting, filtering and page-offsets in this API.

**Additional context**

**Comment by bsushmith** [comment]
Search API has the ability to pass many values for the same data field, but it does a search on ES and it's not filtering per se. Also, search API doesn't support pagination or offset. 

`GetAllAssets` has ability to filter but it's just that it filters in an opinionated way, which is not apparent through the API spec. This change will help in reducing that and increasing filter use-cases.

**Comment by StewartJingga** [comment]
> Search API has the ability to pass many values for the same data field, but it does a search on ES and it's not filtering per se. Also, search API doesn't support pagination or offset.
> 
> `GetAllAssets` has ability to filter but it's just that it filters in an opinionated way, which is not apparent through the API spec. This change will help in reducing that and increasing filter use-cases.

I see, I can see the use case is clear, my only concern is more to do we want to focus more on `GetAllAssets` for this feature or should it be more on `Search` API.

Other than that I really don't have a strong opinion, wdyt @ravisuhag @sudo-suhas ?

**Comment by ravisuhag** [comment]
I think it will be ok to have this on this API unless it affects the performances.

**Comment by sudo-suhas** [comment]
My concern was w.r.t implementation where each value in the map can be CSV. This can be a problem if any of the individual values of a field already contain a comma. I would instead prefer we add a new field `GetAllTypesRequest.DataV2`  of type `map[string][]string`. We can deprecate the existing field without breaking backward compatibility by translating `Data` to `DataV2` if it is present in the request.
