### ISSUE TITLE
add asset data.properties.attributes in lineage response

### ISSUE THREAD

**Issue by bsushmith** [odpf/compass#206]
**Is your feature request related to a problem? Please describe.**
In meteor we support enriching asset by adding user configurable(through recipe) key-value pairs to asset metadata. This is generally stored in `asset.data.properties.attributes` field. Add support to return back these data points as part of lineage API.

This can help the caller to do additional actions if necessary on the lineage response, based on the attributes.

**Comment by ravisuhag** [comment]
Until we plan more proper attributes to return in search, lineage vs list. This is de-prioritized.
