### ISSUE TITLE
Better multi-tenant support

### ISSUE THREAD

**Issue by kushsharma** [odpf/compass#208]
**Is your feature request related to a problem? Please describe.**
In Compass when inserting a new Asset, the payload looks as follows
```
{
  "urn": "main-postgres:my-database.orders",
  "type": "table",
  "service": "postgres",
  "name": "orders",
  "data": {
    "database": "my-database",
    "namespace": "tenant-1"
  }
}
``` 
Separating assets based on tenants can only be done via `data` key/value attributes. While insertion, a key of `namespace` can be utilized, and querying can use a filter of `namespace` as the key. This design looks suitable for small-scale implementations but will start to break as the number of tenants increases. Compass uses two data repositories(Postgres & ES) and both stores are suffering from this flaw that will eventually limit the scale.

### Postgres
One quick fix is to create a `btree` index on `(data->namespace)` of the `assets` table. It can improve the querying speed but still, the design doesn't mandate whether each asset really belongs to a namespace or not. The next step is, adding an application-level handler that will simply add a default `namespace` id if not supplied in the insert request. That means we are mandating a key in a blob of JSON data that was supposed to be generic. Okay, maybe we can add this in the documentation but I still feel we should have a dedicated column of the `namespace` which in the future can be utilized for sharding a database if ever Postgres grew to a substantial size which I feel it will looking at the use-case of what Compass is doing(ingesting whole company's metadata).

### ElasticSearch
Compass for each service type(kafka/table/etc) creates its own index in ElasticSearch. All the tenants share all the shards and indexes across the ES cluster. To segregate tenant-specific queries, Compass uses filters just like Postgres over `data` keys. One problem with this design is all the queries span across the complete ES cluster for searching which document belongs to which tenant. For example, if tenant `A` has 1 GB of data but tenant `B` has 100 GB of data, both tenants whenever Compass makes a request will search 101 GB of documents. Ideally, tenant A search should limit it to 1 GB(or in the worst case couple of more GBs) but not the whole cluster size.

![image](https://user-images.githubusercontent.com/3647166/220151986-cec1e44c-ebe4-4a6b-9af1-ad6f94c91919.png)

**Describe the solution you'd like**
To support multi-tenant from the ground up, I propose

### Postgres
Adding a new column for the `namespace` in `Assets` table. Our APIs can choose to accept the `namespace` as one more field, if it's passed in the request it will be populated in the database but if not it can be set as null uuid(0000...). So in the case where users don't care about multi-tenancy, everything will be pushed to a single null namespace but individual tenants can also query assets by namespace id.

### ElasticSearch
One `index` for all services and tenants but all requests should be routed to a unique `shard` for a single tenant. Compass can categorize a tenant into two tires, `shared` and `dedicated`. For shared tenants, all the requests will be routed by namespace id over a single `shard` in an `index`. For dedicated tenants, each tenant can have its own index. Note, a single `index` will have N number of `types` same as the number of `Services` supported in Compass. This design will ensure, all the document insert/query requests are only confined to a single shard(in case of shared) or a single index(in case of dedicated).

![image](https://user-images.githubusercontent.com/3647166/220151889-399a2fd5-a397-4b7d-bd1f-a412a8aa8990.png)

**Comment by sudo-suhas** [comment]
> This design looks suitable for small-scale implementations but will start to break as the number of tenants increases.

I don't think the issues raised for individual datastores justofy this satisfactorily.

> One quick fix is to create a btree index on (data->namespace) of the assets table. It can improve the querying speed but still, the design doesn't mandate whether each asset really belongs to a namespace or not. 

In my opinion, we are jumping to solutions without clearly demarkating the problem. One problem I see today with our queries being run on the database is that some of them could be offloaded to Elasticsearch. Once you limit the queries against the database to create/update and fetch by ID/version, where is the issue with performance?

> One problem with this design is all the queries span across the complete ES cluster for searching which document belongs to which tenant.

This is not correct. When executing a term query in Elasticsearch, the query is executed against all shards that **contain the relevant data.** However, Elasticsearch is designed to distribute data across shards based on the hash of the document's primary key, so the term query will typically only need to be executed against a subset of the total number of shards.

The exact number of shards that need to be searched will depend on the specific query and the distribution of data across shards. For example, if the term being searched for is very common, it may be present in a large number of shards and require a significant amount of searching. Conversely, if the term is very rare, it may only be present in a small number of shards. In our case, applying a term query for something like a `project_id` field already ensures we query the minimum number of shards required.

Overall, Elasticsearch is optimized to minimize the number of shards that need to be searched for a given query, while still ensuring that all relevant data is included in the search results.

The proposed solution brings a significant breaking change for a problem that does not exist. In it's current form, I would not be in favor of merging it in.

cc: @StewartJingga

**Comment by kushsharma** [comment]
> When executing a term query in Elasticsearch, the query is executed against all shards that contain the relevant data.

@sudo-suhas Can you explain how elasticsearch knows to search only shards containing the data query is looking for? Help me understand the current design, if the data is hashed using its `_id` primary key(as you said) which is distributed in 5 shards(default number) and the input that we got from a user is a `text` and `project_id`. Now the input query contains a search text as "orders table" and a project `uuid`, in this case, how will ES select which shard to query?

> For example, if the term being searched for is very common, it may be present in a large number of shards and require a significant amount of searching. Conversely, if the term is very rare, it may only be present in a small number of shards.

How can ES know a term is rare or common before actually searching all shards? Does ES have some pre-search optimization phase? Can you explain this in detail?

**Comment by sudo-suhas** [comment]
I would request you invest some time and effort in reading through documentation and blog posts concerning Elasticsearch. Suggesting architectural changes without understanding key characteristics, and showing benchmarks for performance issues, is not going to be productive.

At the very basic, shards are used for partitioning data and that data in this case is inverted indices. Inverted indices can be used to look up all the documents that contain a specific phrase. Elasticsearch uses hashing to identify the shard that contains the relevant data for the given search term. While I am not very familiar with the internals, since it is a mature and performant product, I would imagine that it would be capable of identifying the intersection of shards that contain `text` and `project_id` to limit the search.

**Comment by sudo-suhas** [comment]
I am trying to find documentation that definitively answers the question of whether queries need to be executed on all shards. If you are able to find it, please share.

**Comment by sudo-suhas** [comment]
> When executing a term query in Elasticsearch, the query is executed against all shards that contain the relevant data.

I think I was wrong about this. Each shard is a lucene index into which documents are indexed. And documents are distributed based on hashing. Therefore, each query would need to look up each shard to check if there are any documents in that shard that match the search query.

That said, I am still not convinced with the proposed approach. Do we have any benchmarks or evidence to show that there is a problem with queries being run on all shards? Have we looked at the optimisation strategies recommended by Elasticsearch?

**Comment by sudo-suhas** [comment]
Also see https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html

**Comment by ravisuhag** [comment]
After discussion we are approaching this RLS and shared+ dedicated indexes for multi tenancy.
