### ISSUE TITLE
What's the use-case for URN field in Asset?

### ISSUE THREAD

**Issue by kushsharma** [odpf/compass#212]
I fail to understand how `urn` field is being used by users of Compass. This is externally injected to identify each asset uniquely by a client but in what cases I would do that?

**Comment by ravisuhag** [comment]
Meteor needs to understand the URN to inject and update assets. As it can't rely on compass internal id to identify which asset to update.

**Comment by kushsharma** [comment]
Got it, so it's used to upsert a document. Thanks.
