### ISSUE TITLE
Getting asset's first version return no record for the asset error

### ISSUE THREAD

**Issue by Chief-Rishab** [odpf/compass#215]
**Describe the bug**
Getting a previous version of asset on the first version(`0.1`) is returning `no such record /:assetID` but works fine for other versions

**To Reproduce**
1. Create a new asset
2. Update the asset to create new version
3. Get asset's previous version with version id `0.1`

**Expected behavior**
Should return the first version of the asset

**Comment by 2FJDJD** [comment]
https://user-images.githubusercontent.com/128664730/229960176-a503b272-a891-4cea-80ed-ac68cff9aa55.mp4

https://github.com/orgs/odpf/projects/12/views/2?pane=issue&itemId=22062084
