### ISSUE TITLE
Question: Why do we limit type of asset?

### ISSUE THREAD

**Issue by kushsharma** [odpf/compass#219]
**Is your feature request related to a problem? Please describe.**
I want to understand the logic behind limiting the `type` of assets to a fixed number of items. What benefit are we getting out of it? 
I am talking about asset types available in code [here](https://github.com/odpf/compass/blob/65b8328f9effa48d561833d7087fb6855954e53f/core/asset/type.go)

**Describe the solution you'd like**
What if we make this generic and accept all `type` values, we would still be able to group the same types if needed. What would we lose? This is to make the compass more flexible.

**Comment by ravisuhag** [comment]
@kushsharma a standard type is useful for clients to show and render type of data. and also to prevent injecting just any type. Do you see any major benefit of allowing any type.
